# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
        authentication_handler:
            class: AppBundle\Controller\AuthenticationHandler
            public: false
            arguments:
                - @router
                - @session
        twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }
        twig.extension.text:
            class: Twig_Extensions_Extension_Text
            tags:
                - { name: twig.extension }
    # le service de constructeur de menus. Peut servir à créer plusieurs menus
        mpt.menu_builder:
            class: AppBundle\Menu\MenuBuilder
            arguments: ["@knp_menu.factory"]

    # votre menu
        mpt.menu.breadcrumb:
            class: Knp\Menu\MenuItem
            factory_service: mpt.menu_builder # le service du constructeur vu juste au-dessus
            factory_method: createBreadcrumbMenu # la méthode appelée pour générer le menu
            arguments: ["@request"]
            scope: request
            tags:
                - { name: knp_menu.menu, alias: breadcrumb } # L'alias est utilisé dans le template
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]